CREATE DATABASE IF NOT EXISTS lithography_control;
USE lithography_control;
CREATE TABLE IF NOT EXISTS machines(id BIGINT PRIMARY KEY AUTO_INCREMENT,name VARCHAR(128) NOT NULL,mode VARCHAR(32) NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sensors(id BIGINT PRIMARY KEY AUTO_INCREMENT,machine_id BIGINT NOT NULL,name VARCHAR(128) NOT NULL,unit VARCHAR(32),FOREIGN KEY(machine_id) REFERENCES machines(id));
CREATE TABLE IF NOT EXISTS sensor_readings(id BIGINT PRIMARY KEY AUTO_INCREMENT,sensor_id BIGINT NOT NULL,value DOUBLE NOT NULL,recorded_at TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP(6),FOREIGN KEY(sensor_id) REFERENCES sensors(id));
CREATE TABLE IF NOT EXISTS audit_log(id BIGINT PRIMARY KEY AUTO_INCREMENT,actor VARCHAR(128),action VARCHAR(128),target VARCHAR(256),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP);
